ALTER TABLE tools
ADD COLUMN clicks INT DEFAULT 0;

ALTER TABLE tools
ADD COLUMN featured BOOLEAN DEFAULT false;

ALTER TABLE tools
ADD COLUMN premium BOOLEAN DEFAULT false;

ALTER TABLE tools
ADD COLUMN trending_score INT DEFAULT 0;
